### ISSUE TITLE
Add exercises count to guides endpoint

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-bibliotheca-api#67] opened 2016-10-21 20:25 UTC

**Comment by flbulgarelli** [comment] 2017-02-01 16:37
Why?

**Comment by flbulgarelli** [comment] 2017-02-01 16:39
Moreover, we are deprecating APIs for internal usage in favor of queue consumption

**Comment by flbulgarelli** [comment] 2017-02-01 16:42
I assume this is the root cause: https://github.com/mumuki/mumuki-platform/issues/184. So I am closing this issue as its duplicate.

**Closed by flbulgarelli** 2017-02-01 16:42 UTC
